AWSTemplateFormatVersion: "2010-09-09"
Description: "This template will be used to launch jenkins server and grafana server"

Parameters:
  AMI:
    Type: AWS::EC2::Image::Id
    Default: "ami-0cd59ecaf368e5ccf"
  InstanceType:
    Type: String
    Default: "t3.large"
  KeyPair:
    Type: String
    Default: "us_key_pair"
  SubnetId:   
    Type: String
    Default: "subnet-029ac39a2a79c077e"
  SecurityGroupIds:
    Type: String
    Default: "sg-02610fb50b5db30a1"

Resources:   
  Sivajenkinsandgrafana:
    Type: AWS::EC2::Instance
    Properties:                                     # configuration and userdata gives you the properties
      ImageId: !Ref AMI
      KeyName: !Ref KeyPair
      InstanceType: !Ref InstanceType
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            echo "Creating Jenkins and grafana server"
            sudo apt-get update -y
            sudo apt install docker.io -y
            sudo usermod -aG docker ubuntu
            sudo docker pull jenkins/jenkins
            sudo docker run -itd --name jenkins -p 8080:8080 jenkins/jenkins
            sudo docker pull grafana/grafana
            sudo docker run -itd --name grafana -p 3000:3000 grafana/grafana
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 30
            VolumeType: gp3
            Iops: 3000
            DeleteOnTermination: true          
      Tags: 
        - Key: CreatedBy
          Value: Siva
      NetworkInterfaces: 
      - AssociatePublicIpAddress: "true"
        DeviceIndex: "0"
        GroupSet: 
          - !Ref SecurityGroupIds
        SubnetId: !Ref SubnetId
